-- The pictures that come with the game. Each one is drawn
-- as letters, one letter per big square: a dot is empty,
-- every other letter is a color from colors.lua.
-- Every row in a picture must be the same length.

PICTURES = { }

PICTURES.cat = { }
PICTURES.cat[1] = "..YY....YY.."
PICTURES.cat[2] = "..YMY..YMY.."
PICTURES.cat[3] = "..YYYYYYYY.."
PICTURES.cat[4] = ".YYWYYYYWYY."
PICTURES.cat[5] = "YYWWKYYKWWYY"
PICTURES.cat[6] = ".YYYYMMYYYY."
PICTURES.cat[7] = "..YYYYYYYY.."
PICTURES.cat[8] = "..YYYYYYYY.."
PICTURES.cat[9] = "..YYYYYYYY.."
PICTURES.cat[10] = "..YYYYYYYY.."
PICTURES.cat[11] = "..YYY..YYY.."
PICTURES.cat[12] = "..YYY..YYY.."

PICTURES.turtle = { }
PICTURES.turtle[1] = ".....GG....."
PICTURES.turtle[2] = "GGG.GGGG.GGG"
PICTURES.turtle[3] = "GGGyKGGKyGGG"
PICTURES.turtle[4] = ".GGGggggGGG."
PICTURES.turtle[5] = "..GggyyggG.."
PICTURES.turtle[6] = "..ggyGGygg.."
PICTURES.turtle[7] = "..gyGggGyg.."
PICTURES.turtle[8] = "..gyGggGyg.."
PICTURES.turtle[9] = "..GgyGGygG.."
PICTURES.turtle[10] = ".GGggyyggGG."
PICTURES.turtle[11] = "GGG.gggg.GGG"
PICTURES.turtle[12] = "GGG..GG..GGG"

PICTURES.ufo = { }
PICTURES.ufo[1] = "....CCCC...."
PICTURES.ufo[2] = "...CCCCCC..."
PICTURES.ufo[3] = "..CCCCCCCC.."
PICTURES.ufo[4] = ".wwwwwwwwww."
PICTURES.ufo[5] = "wwwwwwwwwwww"
PICTURES.ufo[6] = "wMMwwMMwwMMw"
PICTURES.ufo[7] = ".wwwwwwwwww."
PICTURES.ufo[8] = "..wwwwwwww.."
PICTURES.ufo[9] = "...w....w..."
PICTURES.ufo[10] = "..MM....MM.."
PICTURES.ufo[11] = "............"

PICTURES.mouse = { }
PICTURES.mouse[1] = ".WWW....WWW."
PICTURES.mouse[2] = "WMMMW..WMMMW"
PICTURES.mouse[3] = "WWMMWWWWMMWW"
PICTURES.mouse[4] = ".WWwwWWwwWW."
PICTURES.mouse[5] = "..wwKwwKww.."
PICTURES.mouse[6] = "...wwMMww..."
PICTURES.mouse[7] = "...WwwwwW.WW"
PICTURES.mouse[8] = "..WWWwwWWW.W"
PICTURES.mouse[9] = "..WWWwwWWW.W"
PICTURES.mouse[10] = "..WWWwwWWWWW"
PICTURES.mouse[11] = "...WW..WW..."
PICTURES.mouse[12] = "....W..W...."

PICTURES.star = { }
PICTURES.star[1] = "....Y...."
PICTURES.star[2] = "...YYY..."
PICTURES.star[3] = "YY.YWY.YY"
PICTURES.star[4] = "YWYYWYYWY"
PICTURES.star[5] = ".YWYYYWY."
PICTURES.star[6] = "..YYYYY.."
PICTURES.star[7] = ".YWYYYWY."
PICTURES.star[8] = "YWYY.YYWY"
PICTURES.star[9] = "YY.....YY"

PICTURES.cheese = { }
PICTURES.cheese[1] = ".....yyyyy"
PICTURES.cheese[2] = "...yyyyYYY"
PICTURES.cheese[3] = ".yyyYKYYYY"
PICTURES.cheese[4] = "yyYyYYYKYK"
PICTURES.cheese[5] = "YYYYYYYYYY"
PICTURES.cheese[6] = "YYYYKYYYK."
PICTURES.cheese[7] = "YKYYYYYYY."
PICTURES.cheese[8] = "YYYKKYYY.."
PICTURES.cheese[9] = "YYYKKYY..."
PICTURES.cheese[10] = "YYYYYY...."

PICTURES.apple = { }
PICTURES.apple[1] = "....G.gg.."
PICTURES.apple[2] = ".RR.GggRR."
PICTURES.apple[3] = "rRRRGgRRRR"
PICTURES.apple[4] = "rrRRRRRRRR"
PICTURES.apple[5] = "rrWRRRRRRR"
PICTURES.apple[6] = "rrWRRRRRRR"
PICTURES.apple[7] = "rrrRRRRRRR"
PICTURES.apple[8] = ".rrrRRRRR."
PICTURES.apple[9] = "..rrrrRR.."
PICTURES.apple[10] = "...rrrr..."

PICTURES.dog = { }
PICTURES.dog[1] = "..Tn...nT.."
PICTURES.dog[2] = "...nTnTn..."
PICTURES.dog[3] = "...TKnKT..."
PICTURES.dog[4] = "...nTKTn..."
PICTURES.dog[5] = "...TnMnT.TT"
PICTURES.dog[6] = "...TnnnT.T."
PICTURES.dog[7] = "...TnTnT.n."
PICTURES.dog[8] = "...TT.TTnn."
PICTURES.dog[9] = "..TTT.TTT.."

PICTURES.fox = { }
PICTURES.fox[1] = "..S......S...."
PICTURES.fox[2] = "..SS....SS...."
PICTURES.fox[3] = "..SOS..SOS...."
PICTURES.fox[4] = ".OSSWSSWSSO..."
PICTURES.fox[5] = "OSSWaSSaWSSO.."
PICTURES.fox[6] = ".OSSWMMWSSO..."
PICTURES.fox[7] = "..SOSSSSOS...."
PICTURES.fox[8] = "..SOOOOOOS.SOO"
PICTURES.fox[9] = "..SSOOOOSS.SSO"
PICTURES.fox[10] = "..SSSOOSSSSSSO"
PICTURES.fox[11] = "..SOS..SOSSSS."
PICTURES.fox[12] = "..OOO..OOOSSS."

-- The first fox, kept as its own picture. Nothing a child was
-- given is taken away when a redrawn version arrives.
PICTURES.pokefox = { }
PICTURES.pokefox[1] = "..S...S....."
PICTURES.pokefox[2] = ".SSS.SSS...."
PICTURES.pokefox[3] = "YSSSSSSSSY.."
PICTURES.pokefox[4] = "YSKSSSSKSY.."
PICTURES.pokefox[5] = "YSSSMMSSSY.."
PICTURES.pokefox[6] = ".SYYYYYYS..."
PICTURES.pokefox[7] = ".SYYYYYYS.YY"
PICTURES.pokefox[8] = "SSYYYYYYSSYY"
PICTURES.pokefox[9] = ".SYYYYYYSSY."
PICTURES.pokefox[10] = ".SSYSSYSS..."
PICTURES.pokefox[11] = "..YYSSYY...."

PICTURES.chicken = { }
PICTURES.chicken[1] = ".....S....."
PICTURES.chicken[2] = "....KWK...."
PICTURES.chicken[3] = "....YYY...."
PICTURES.chicken[4] = "....WYW...."
PICTURES.chicken[5] = "....WSW...."
PICTURES.chicken[6] = "....WSW...."
PICTURES.chicken[7] = "...YWWWY..."
PICTURES.chicken[8] = "..YWWWWWY.."
PICTURES.chicken[9] = "..YWWWWWY.."
PICTURES.chicken[10] = "..YWYYYWY.."
PICTURES.chicken[11] = "...YY.YY..."
PICTURES.chicken[12] = "....O.O...."
PICTURES.chicken[13] = "...OO.OO..."

PICTURES.squish = { }
PICTURES.squish[1] = "..A.."
PICTURES.squish[2] = "..A.."
PICTURES.squish[3] = "..A.."
PICTURES.squish[4] = ".vvv."
PICTURES.squish[5] = "vKvKv"
PICTURES.squish[6] = "vvSvv"
PICTURES.squish[7] = "vSSSv"
PICTURES.squish[8] = "vvSvv"
PICTURES.squish[9] = "vSSSv"
PICTURES.squish[10] = ".vvv."

PICTURES.tree = { }
PICTURES.tree[1] = ".....GG....."
PICTURES.tree[2] = "....GGGG...."
PICTURES.tree[3] = "...GGGGGG..."
PICTURES.tree[4] = ".GGGGGGGGGG."
PICTURES.tree[5] = ".GGGGGGGGGG."
PICTURES.tree[6] = "...GGGGGG..."
PICTURES.tree[7] = ".....nn....."
PICTURES.tree[8] = ".....nn....."
PICTURES.tree[9] = ".....nn....."
PICTURES.tree[10] = ".....nn....."
PICTURES.tree[11] = "............"

PICTURES.dino = { }
PICTURES.dino[1] = ".......GGG.."
PICTURES.dino[2] = "......GGGGG."
PICTURES.dino[3] = "......GKGGG."
PICTURES.dino[4] = "g.....GGGGG."
PICTURES.dino[5] = "gg...GGGGG.."
PICTURES.dino[6] = "gGGGGGGGG..."
PICTURES.dino[7] = "GGGGGGGGGG.."
PICTURES.dino[8] = "gGGGGGGGGG.."
PICTURES.dino[9] = ".GGGGGGGG..."
PICTURES.dino[10] = "..GG..GG...."
PICTURES.dino[11] = "..GG..GG...."

PICTURES.diplo = { }
PICTURES.diplo[1] = ".GGG.........."
PICTURES.diplo[2] = ".GKG.........."
PICTURES.diplo[3] = "..GG.........."
PICTURES.diplo[4] = "..GG.........."
PICTURES.diplo[5] = "..GG.......GG."
PICTURES.diplo[6] = "..GGGGGGGGGGG."
PICTURES.diplo[7] = "..GGGGGGGGGG.."
PICTURES.diplo[8] = "...GG....GG..."
PICTURES.diplo[9] = "...gg....gg..."

PICTURES.tornado = { }
PICTURES.tornado[1] = "AAAAAAAAAAAA"
PICTURES.tornado[2] = "wwwwwwwwwwww"
PICTURES.tornado[3] = ".AAAAAAAAAA."
PICTURES.tornado[4] = "..wwwwwwww.."
PICTURES.tornado[5] = "...AAAAAA..."
PICTURES.tornado[6] = "....wwww...."
PICTURES.tornado[7] = "....AAAA...."
PICTURES.tornado[8] = ".....ww....."
PICTURES.tornado[9] = ".....AA....."
PICTURES.tornado[10] = ".....ww....."
PICTURES.tornado[11] = "......A....."

PICTURES.meteor = { }
PICTURES.meteor[1] = ".....R..R...."
PICTURES.meteor[2] = "...RYYRRYR..."
PICTURES.meteor[3] = "..ROOOOOOR..."
PICTURES.meteor[4] = ".RYOAAAAOOR.."
PICTURES.meteor[5] = ".ROAAaAAAOR.."
PICTURES.meteor[6] = ".RYOAAAaAOR.."
PICTURES.meteor[7] = "..ROAAAAOOR.."
PICTURES.meteor[8] = "...ROOOOOR..."
PICTURES.meteor[9] = "....RRRRR...."

PICTURES.spider = { }
PICTURES.spider[1] = "..W...W.."
PICTURES.spider[2] = "...vvv..."
PICTURES.spider[3] = "YYYvvvYYY"
PICTURES.spider[4] = "Y..vvv..Y"
PICTURES.spider[5] = "...vvv..."
PICTURES.spider[6] = "YYYvvvYYY"
PICTURES.spider[7] = "Y.......Y"

PICTURES.hamster = { }
PICTURES.hamster[1] = ".N....N."
PICTURES.hamster[2] = ".NNNNNN."
PICTURES.hamster[3] = ".NbNNbN."
PICTURES.hamster[4] = ".NNYYNN."
PICTURES.hamster[5] = "..NNNN.."
PICTURES.hamster[6] = ".NNNNNN."
PICTURES.hamster[7] = "NNKNNKNN"
PICTURES.hamster[8] = "NNKNNKNN"
PICTURES.hamster[9] = ".NNNNNN."

PICTURES.rocket = { }
PICTURES.rocket[1] = ".....CC....."
PICTURES.rocket[2] = "....CCCC...."
PICTURES.rocket[3] = "....CCCC...."
PICTURES.rocket[4] = "...CCCCCC..."
PICTURES.rocket[5] = "..BBwwwwBB.."
PICTURES.rocket[6] = ".BBBwMMwBBB."
PICTURES.rocket[7] = "BBB.WMMw.BBB"
PICTURES.rocket[8] = "B..wWwwww..B"
PICTURES.rocket[9] = "..wwwwwwww.."
PICTURES.rocket[10] = ".wwwwwwwwww."
PICTURES.rocket[11] = "...WW..WW..."
PICTURES.rocket[12] = "...vM..Mv..."

PICTURES.fish = { }
PICTURES.fish[1] = "...CCC...."
PICTURES.fish[2] = "....CCC..."
PICTURES.fish[3] = "CCC..CCC.."
PICTURES.fish[4] = ".CC.CCWYC."
PICTURES.fish[5] = "..CCCWYKYC"
PICTURES.fish[6] = "..CCCCWYCC"
PICTURES.fish[7] = ".CC.CCCCC."
PICTURES.fish[8] = "CCC..CCC.."
PICTURES.fish[9] = "....CCC..."
PICTURES.fish[10] = "...CCC...."

PICTURES.bee = { }
PICTURES.bee[1] = "..A..A.."
PICTURES.bee[2] = "..AAAA.."
PICTURES.bee[3] = "CCYYYYCC"
PICTURES.bee[4] = "CCAAAACC"
PICTURES.bee[5] = ".CYYYYC."
PICTURES.bee[6] = "..AAAA.."
PICTURES.bee[7] = "...AA..."

PICTURES.rainbow = { }
PICTURES.rainbow[1] = "....MMMMM...."
PICTURES.rainbow[2] = "...MCCCCCM..."
PICTURES.rainbow[3] = "..MCGGGGGCM.."
PICTURES.rainbow[4] = ".MCGYYYYYGCM."
PICTURES.rainbow[5] = "MCGYRRRRRYGCM"
PICTURES.rainbow[6] = "MCGYR...RYGCM"
PICTURES.rainbow[7] = "MCGYR...RYGCM"

PICTURES.acorn = { }
PICTURES.acorn[1] = "...g..."
PICTURES.acorn[2] = "...g..."
PICTURES.acorn[3] = "..ggg.."
PICTURES.acorn[4] = ".ggggg."
PICTURES.acorn[5] = "ggggggg"
PICTURES.acorn[6] = ".nnnnn."
PICTURES.acorn[7] = ".nnnnn."
PICTURES.acorn[8] = ".nnnnn."
PICTURES.acorn[9] = "..nnn.."
PICTURES.acorn[10] = "...n..."

-- The lemon that eats, with the eyes and teeth to prove it.
PICTURES.lemon = { }
PICTURES.lemon[1] = ".GG........"
PICTURES.lemon[2] = ".GG........"
PICTURES.lemon[3] = ".GGYYYYYYY."
PICTURES.lemon[4] = "..YKYYYKYYY"
PICTURES.lemon[5] = "..YYYYYYYYY"
PICTURES.lemon[6] = "..YYKKKKKYY"
PICTURES.lemon[7] = "....KWKWKYY"
PICTURES.lemon[8] = "....YYYYYY."

PICTURES.smallfish = { }
PICTURES.smallfish[1] = "AAAAA.AA"
PICTURES.smallfish[2] = "AKAAAAAA"
PICTURES.smallfish[3] = "AAPKAAAA"
PICTURES.smallfish[4] = "KKKKAAAA"
PICTURES.smallfish[5] = "AAAAA.AA"

PICTURES.droplet = { }
PICTURES.droplet[1] = "....B...."
PICTURES.droplet[2] = "...BCB..."
PICTURES.droplet[3] = "...BCB..."
PICTURES.droplet[4] = "..BCCCB.."
PICTURES.droplet[5] = ".BCCCCCB."
PICTURES.droplet[6] = ".BCCWCCB."
PICTURES.droplet[7] = ".BCCCCCB."
PICTURES.droplet[8] = "..BCCCB.."
PICTURES.droplet[9] = "...BBB..."

PICTURES.lightning = { }
PICTURES.lightning[1] = "....YYY.."
PICTURES.lightning[2] = "...YYY..."
PICTURES.lightning[3] = "..YYY...."
PICTURES.lightning[4] = ".YYYYYY.."
PICTURES.lightning[5] = "...YYYY.."
PICTURES.lightning[6] = "....YYY.."
PICTURES.lightning[7] = "...YYY..."
PICTURES.lightning[8] = "..YYY...."
PICTURES.lightning[9] = ".YY......"
